### ISSUE TITLE
Questions on the performance results on a simple pagerank

### ISSUE THREAD

**Issue by cheonruen** [epfl-labos/chaos#1]
Hi,

I am testing the system Chaos in the following setup. It's a simple scalability test increasing the number of worker threads. I used only 1 machine and RMAT-27 dataset.

**CMDs**:
benchmark_driver -g test -b page rank —page rank::niters 1 -a -p 1 —physical_memory 1073741824
benchmark_driver -g test -b page rank —page rank::niters 1 -a -p 16 —physical_memory 1073741824

The elapsed time was 929.5 sec (-p 1) and 790.1 secs (-p 16).
It may not show the ideal linear scalability but the results are somewhat hard to understand. Did I miss something here?

**HW spec** of the machine used for tests.
**CPU**: 2 \* Intel Xeon 2.2Ghz (8 cores): Total 16 cores
**RAM**: 32 GB
**Disk**: SSD (Read: ~ 300 MB/sec)

**Comment by bindsch** [comment]
Hi cheonruen!

This is pretty much expected as Chaos is designed to scale with the amount of storage (or machines). If you want a system that scales with the number of cores on a single machine, you probably want an in-memory graph processing system.

**Comment by cheonruen** [comment]
Thanks for your prompt response,
- Does that mean Chaos might already saturate the disk bandwidth even with a single thread? (I think it should scale even on a single machine if a single worker thread is not fully utilizing the disk i/o bandwidth.) I will further check the disk bandwidth utilization.
- May I ask how many iterations you ran in PageRank query on (Table 1 on your paper [[Link](http://sigops.org/sosp/sosp15/current/2015-Monterey/089-roy-online.pdf)]) ?

**Comment by bindsch** [comment]
It probably gets close to saturating it with a single thread, but you will need a few more to make sure of that. Of course, the system is designed with multiple machines in mind, so there you will probably saturate disks even with a single thread.

We ran 5 iterations of PageRank for all results reported in the paper.
