### ISSUE TITLE
Rmat graph generator: duplicated edge

### ISSUE THREAD

**Issue by seongyun-ko** [epfl-labos/chaos#2]
Hi,

I used the RMAT graph generator in this repository.
I found that it generated a lot of duplicated edges.

How did you handle those?
For example, you performed experiments on such data sets with 1 trillion edges.
Does it include the duplicated edges?

thanks,

**Comment by bindsch** [comment]
Yes, the RMAT generator generates duplicate edges by construction. Chaos does not try to do anything special with duplicate edges (i.e. we don't filter duplicates or anything) as this might affect the correctness of some algorithms.

The 1T edge experiments we reported in the SOSP paper include unfiltered duplicates.
