### ISSUE TITLE
Cannot compile&&run ConnectedComponent Algorithm

### ISSUE THREAD

**Issue by cheonruen** [epfl-labos/chaos#3]
Hi, I am trying to run CC algorithm on the undirected graph.

I first uncommented the 159~160 lines @ /benchmarks/driver.cpp to include CC in compilation.
Even with that, I still cannot compile CC algorithm code.

I found that some important functions are missing in cc.hpp
such as vertex_apply(...). Could you take a look at it?

Thanks,

**Comment by bindsch** [comment]
Hi,

The CC algorithm is called WCC. That one is uncommented.

Cheers,

-Laurent
