### ISSUE TITLE
How to process graph without weight?

### ISSUE THREAD

**Issue by hustallenlee** [epfl-labos/chaos#5]
The rmat tool generates graph with weighted edges, how could i generates  graph without weighted edges and process it? sorry but the makefile does not has the configurable macro flag and benchmark_driver has no configurable parameters too.

**Comment by bindsch** [comment]
You will want to comment out `CFLAGS += -DWEIGHT` in the generators Makefile.

**Comment by hustallenlee** [comment]
oh! great, thank you very much.
