### ISSUE TITLE
boost::exception

### ISSUE THREAD

**Issue by shuangsong1990** [epfl-labos/chaos#7]
I encountered a problem when I am running chaos by using the example command "./benchmark_driver -g test -b pagerank --pagerank::niters 10 -a -p 1 --physical_memory 268435456"

The log of this job: 
<INFO 7f725cc64780> 2017-09-05 22:44:59 STARTUP
<INFO 7f725cc64780> CORE::GRAPH test
<INFO 7f725cc64780> CORE::ALGORITHM pagerank
<INFO 7f725cc64780> CORE::VERTEX_STRIPING OFF
<INFO 7f725cc64780> SG-DRIVER-ORIGINAL
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::property_tree::ptree_bad_data> >'
  what():  conversion of data to type "m" failed
Aborted (core dumped)

Have you guys seen it before?

**Comment by bindsch** [comment]
Not that I recall. Where in the code does the core dump tell you the problem occurred? Also, what boost version are you using?

**Comment by shuangsong1990** [comment]
The boost version is 1.54, and I also installed a boost-numeric-bindings separately. 
I haven't figured out where in the code cause the problem yet

Shuang

**Comment by marcinz** [comment]
Was this issue resolved? We have seen the same problem.

**Comment by marcinz** [comment]
OK, I got it. For whoever else reaches this page, the problem for me was comments starting with "#" in the slipstore.ini file. Doh.
